# Generated by Django 3.1.7 on 2021-03-16 10:06

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=255, verbose_name='sender name')),
                ('webhook_link', models.CharField(max_length=255, verbose_name='webhook address')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '09---------'.", regex='^09\\d{9}$')], verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('slug', models.CharField(blank=True, max_length=31, null=True, unique=True, verbose_name='slug')),
                ('sender_phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '09---------'.", regex='^09\\d{9}$')], verbose_name='sender phone number')),
                ('sender_name', models.CharField(max_length=255, verbose_name='sender name')),
                ('receiver_phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '09---------'.", regex='^09\\d{9}$')], verbose_name='receiver phone number')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='receiver name')),
                ('origin_long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='origin longtitude')),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='origin latitude')),
                ('origin_address', models.TextField(verbose_name='origin address')),
                ('destination_long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='destination longtitude')),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='destination latitude')),
                ('destination_address', models.TextField(verbose_name='address')),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('on_way', 'On the way'), ('received', 'received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='status')),
                ('courier', models.ForeignKey(blank=True, help_text='sender', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier', verbose_name='sender')),
                ('sender', models.ForeignKey(help_text='sender', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.collection', verbose_name='sender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
